{{- if .Values.identity.clusterIdentitySecretValueB64 }}
{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.identity.clusterIdentitySecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.identity.clusterIdentitySecretName }} 
  annotations:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
    helm.sh/resource-policy: keep
type: Opaque
data:
  clientSecret: {{ .Values.identity.clusterIdentitySecretValueB64 }}
{{- end }}
{{- end }}
