{{- if .Values.identity.clusterIdentitySecretValueB64 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.identity.clusterIdentitySecretName }} 
  namespace: {{ $.Values.identity.clusterIdentitySecretNamespace }}
  annotations:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
    helm.sh/resource-policy: keep
type: Opaque
data:
  clientSecret: {{ $.Values.identity.clusterIdentitySecretValueB64 }}
{{- end }}
